services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
      SQL_PASSWORD: "ZUNXYMwXH97zrrhpz-PgDw"
    ports:
      - "8000:1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "blog.apphost-6aff93fb59-sql-data"
        read_only: false
    networks:
      - "aspire"
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
      CACHE_PASSWORD: "sGWJHgSfuvWF7mM3GJWyp3"
    ports:
      - "8001:6379"
    networks:
      - "aspire"
  rabbitmq:
    image: "docker.io/library/rabbitmq:4.1-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "zXRbXmSWjYWhk28J38YZSB"
    ports:
      - "8002:5672"
      - "8003:15672"
    networks:
      - "aspire"
  elasticsearch:
    image: "docker.io/library/elasticsearch:8.17.3"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
      ELASTIC_CLIENT_APIVERSIONING: "true"
    ports:
      - "8004:9200"
      - "8005:9300"
    volumes:
      - type: "volume"
        target: "/usr/share/elasticsearch/data"
        source: "blog.apphost-6aff93fb59-elasticsearch-data"
        read_only: false
    networks:
      - "aspire"
  elasticservice:
    image: "${ELASTICSERVICE_IMAGE}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8006"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      ConnectionStrings__BlogDb: "Server=sql,1433;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Initial Catalog=BlogDb"
    ports:
      - "8007:8006"
      - "8009:8008"
    depends_on:
      elasticsearch:
        condition: "service_started"
      sql:
        condition: "service_started"
    networks:
      - "aspire"
  elasticworker:
    image: "${ELASTICWORKER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__elasticsearch: "http://elastic:${ELASTICSEARCH_PASSWORD}@elasticsearch:9200"
      ConnectionStrings__rabbitmq: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      ConnectionStrings__BlogDb: "Server=sql,1433;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Initial Catalog=BlogDb"
    depends_on:
      sql:
        condition: "service_started"
      elasticsearch:
        condition: "service_started"
      rabbitmq:
        condition: "service_started"
    networks:
      - "aspire"
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8010"
      ConnectionStrings__rabbitmq: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      ConnectionStrings__BlogDb: "Server=sql,1433;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Initial Catalog=BlogDb"
      ConnectionStrings__IdentityDb: "Server=sql,1433;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true;Initial Catalog=IdentityDb"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
    ports:
      - "8011:8010"
      - "8013:8012"
    depends_on:
      sql:
        condition: "service_started"
      cache:
        condition: "service_started"
    networks:
      - "aspire"
  webfrontend:
    image: "${WEBFRONTEND_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8014"
      services__elasticservice__http__0: "http://elasticservice:8006"
      services__apiservice__http__0: "http://apiservice:8010"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
    ports:
      - "8015:8014"
      - "8017:8016"
    depends_on:
      elasticservice:
        condition: "service_started"
      apiservice:
        condition: "service_started"
      cache:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  blog.apphost-6aff93fb59-sql-data:
    driver: "local"
  blog.apphost-6aff93fb59-elasticsearch-data:
    driver: "local"
